language: javascript
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t mikemcgarry/frontend .

script:
  - docker run -v /app/node_modules -v $(pwd):/app mikemcgarry/frontend npm run test -- --coverage
