sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t mikemcgarry/frontend .

script:
  - docker run mikemcgarry/frontend -v /app/node_modules -v $(pwd):/app npm run test -- --coverage
  
